### ISSUE TITLE
Make "make install" respect INSTALL_ROOT

### ISSUE THREAD

**Issue by probonopd** [oguzhaninan/Stacer#123]
Currently the following does __not__ work:

```
qmake PREFIX=/usr
make -j$(nproc)
make INSTALL_ROOT=appdir install ; find appdir/
```

https://travis-ci.org/probonopd/Stacer/builds/268721225#L805-L812

```
cd stacer/ && ( test -e Makefile || /opt/qt59/bin/qmake -o Makefile /home/travis/build/probonopd/Stacer/stacer/stacer.pro PREFIX=/usr ) && make -f Makefile install
make[1]: Entering directory `/home/travis/build/probonopd/Stacer/stacer'
make[1]: Nothing to be done for `install'.
make[1]: Leaving directory `/home/travis/build/probonopd/Stacer/stacer'
cat install.sh >install 
chmod a+x install
find: `appdir/': No such file or directory
```

This is needed for making an AppImage on Travis CI using linuxdeployqt.

**Comment by lilianmoraru** [comment]
@probonopd The culprit is here(note that it has a hardcoded path): https://github.com/oguzhaninan/Stacer/blob/3595f550ab58e42f857b711f4f0916419f743f9a/stacer-core/stacer-core.pro#L55
And also `stacer`(the binary) doesn't have an install step.
I fixed this in my [CMake port](https://github.com/oguzhaninan/Stacer/pull/128).

**Comment by probonopd** [comment]
Thanks @lilianmoraru, this will help. I hope it doesn't need newer compilers and stuff?

**Comment by lilianmoraru** [comment]
@probonopd Nah, it has the same requirements as the `qmake` project files but instead of the `qmake` tool, it needs `cmake`.

**Comment by probonopd** [comment]
Why is this ticket closed? Was a solution merged?

**Comment by probonopd** [comment]
@lilianmoraru seems like I can now build using CMake but the artefacts still don't end up in `DESTDIR`:

```
 cmake . -DCMAKE_INSTALL_PREFIX=/usr
 make -j$(nproc)
 make DESTDIR=appdir install ; find appdir/
```

results in:

```
$ make DESTDIR=appdir install ; find appdir/
[  2%] Automatic moc for target stacer-core
[  2%] Built target stacer-core_automoc
[ 38%] Built target stacer-core
[ 41%] Automatic moc, uic and rcc for target stacer
[ 41%] Built target stacer_automoc
[100%] Built target stacer
Install the project...
-- Install configuration: "Debug"
find: `appdir/': No such file or directory
```

https://travis-ci.org/probonopd/Stacer/builds/271183459#L654-L668

**Comment by lilianmoraru** [comment]
@probonopd The CMake `Stacer` build intentionally doesn't allow you to make unoptimized builds when trying to generate the binary for production(`make install`): https://github.com/oguzhaninan/Stacer/blob/native/stacer/CMakeLists.txt#L45
If you plan to offer the AppImage to users, please create an optimized build.

Update, to clarify. This would be an optimized build:
```
cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=/usr .
```

**Comment by probonopd** [comment]
Thank you very much!

**Comment by lilianmoraru** [comment]
@probonopd I added `stacer.desktop` in [`share/applications`](https://github.com/oguzhaninan/Stacer/pull/141/commits/b6feede7207e099dd8b616782395e426fdf0f1ad#diff-0ac15bb75ead9dd03bd1b66ce588e75eR58), try again.
